### ISSUE TITLE
exception when trying to store a value on multipage forms

### ISSUE THREAD

**Issue by DeathAngelDaemon** [bartverdonck/Sitecore-Forms-Extensions#20]
**Describe the bug**
Using a multipage form with the _"store value"_ option on any field leads to an error/exception when trying to get to the next page.

**To Reproduce**
1. Create a form with at least two pages 
2. create a field (e.g. text or email field) on the first page and select the _"store value"_ option under the "Bindings" section
3. add a button with navigation step _"Next"_ selected (on the first page)
4. add anything to the second page (it doesn't matter)
5. add the form (rendering) on a Sitecore item and open it in the Preview mode (or publish it)
6. open the browser developer tools (F12) and go to the _"Network"_ tab
7. fill the (text or email) field with some content and click on the "Next" button
8. see the error in the browser console, click on the xhr request which returns a 500 status type and see the preview of the response (see Screenshot)

**Expected behavior**
I expected the form to show me the next page of the multipage form but also store the value which has been entered in the field.

**Screenshots**
![screen_forms-multipage-500](https://user-images.githubusercontent.com/1528476/48351034-4063f200-e689-11e8-81f5-102fa3ac1482.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 70.0.3538.77

**Additional context**
I don't know if it's worth a new ticket but adding the submit action "Identify contact" (to the "Next" button) also leads to an(other) exception at the same point - undependent of the "store value" exception.

Any help would be appreciate.
Thanks in advance.
Anna

**Comment by bartverdonck** [comment]
Unfortunately, the Tracker.Current is not initialised during form steps. In the case of the store values, that is not really an issue as it is only used to reload the contact and we can skip this until the actual submit.

Bug is fixed by adding an additional null check.

For the identify contact issue. I have also added a null check to make it more redundant, however adding this on a "next"-step will just not work. If you want to use this action, you should add it on the submit action.
