### ISSUE TITLE
Hidden

### ISSUE THREAD

**Issue by bohessner** [bartverdonck/Sitecore-Forms-Extensions#43]
**Hidden field**
When using the Experience editor the hidden field type are hidden (obviously).
When a user/editor want to override the default value with a custom value for his specific page, how would he do that?   

**Experience editor checkbox**
A property checkbox on the "hidden field" named "Visible in Experience editor" and some magic would solve it. Or maybe another solution already exists? 

**Thank you**
for these nice extensions.

**Comment by bartverdonck** [comment]
Hi,

In the forms editor, the hidden fields are already visible so that they can be edited.
![image](https://user-images.githubusercontent.com/5012835/63354483-cd4c8200-c364-11e9-870b-ec4f184d93dc.png)

This is indeed not the case in the experience editor, but the forms are not edited in the experience editor.

I'm not quiet seeing the use case. Can you elaborate?

Best Regards

**Comment by bartverdonck** [comment]
Close due to no feedback.
