### ISSUE TITLE
Google reCaptcha not working

### ISSUE THREAD

**Issue by metz-rda** [bartverdonck/Sitecore-Forms-Extensions#45]
When adding reCaptcha to a form, it shows only in form editor. In Experience Editor and on the rendered page, the Captcha never shows.

1. Go to an existing Form in form editor
2. Add a reCaptcha to the form
3. Ensure it properly shows
4. Save
5. Check existing page to see if Captcha is visible

**Expected behavior**
The captcha should be visible after adding it to the page

Screen shots

![1](https://user-images.githubusercontent.com/53320024/61978655-d6de0680-afbf-11e9-949f-4ef110f5272a.png)
![2](https://user-images.githubusercontent.com/53320024/61978658-d9406080-afbf-11e9-97f8-0c56119ce28d.png)
![3](https://user-images.githubusercontent.com/53320024/61978660-da718d80-afbf-11e9-961d-1d72ba7fc269.png)
![4](https://user-images.githubusercontent.com/53320024/61978664-dc3b5100-afbf-11e9-9cee-322985aa82aa.png)
![5](https://user-images.githubusercontent.com/53320024/61978668-df364180-afbf-11e9-9ea6-0f5a290f3a52.png)

**Comment by bartverdonck** [comment]
Hi, I could not reproduce the issue.

Here are some suggestions based on your screenshots.

1) I assume you are using the latest version of the module (2.2.1?)
2) Script cannot find the loadRecaptchas function. Can you verify that /sitecore%20modules/Web/ExperienceForms/scripts/formsextensions.validate.js is loaded on your page. (Maybe try a hard refresh to get the latest version.

**Comment by ben-norman-codehouse** [comment]
I have Sitecore 9.2 installed and have found that the script tags are rendered after the script in the component so jquery is not yet available and the global javascript variables are not on the page also.
To fix this, I would need to move the inpage javascript underneath the Forms Scripts rendering.
Have you add the js scripts to the head or something to get this working on sc920?

**Comment by ben-norman-codehouse** [comment]
Righto,
2 changes were required to fix this.
#################
Change 1
/Views/FormBuilder/Form.cshtml

Replace whole script tag with the following:
<script type="text/javascript">
            function ready() {
                var $formEl = $("form[data-sc-fxb='@Model.ItemId']");
                if ($formEl.length && typeof $formEl.init_fxbConditions === 'function') {
                    var options = @Html.RenderConditions(Model);
                    $formEl.init_fxbConditions(options);
                }
            }
            document.addEventListener("DOMContentLoaded", ready);
        </script>

#################
Change 2
/Views/FormBuilder/FieldTemplates/ReCaptcha.cshtml

remove the if statement on line 12, 13 and 27 so that the script is rendered on the website as well as in the experience editor

**Comment by bartverdonck** [comment]
Oops, you are correct.
There is indeed a compatibility issue with Sitecore 9.2.
I will look into it, thanks for the code suggestions.

**Comment by bartverdonck** [comment]
Hi, 
This is no bug in the module.
I have tested the issue on Sitecore 9.2 and it works just fine.

The problem with your case is that your layout need to be splitted with an outer layout in order to have the right order of loading.

This is described in the Sitecore documentation. 
https://doc.sitecore.com/developers/92/sitecore-experience-management/en/add-a-form-to-a-webpage.html

Best Regards,

Bart
