### ISSUE TITLE
reCaptchaArray is not defined

### ISSUE THREAD

**Issue by YF82** [bartverdonck/Sitecore-Forms-Extensions#66]
Thank you so much for your effort, we have been use  reCaptcha in our website , and it was working great in ver 2.1 version we upgrade to 2.2.1 and we found below exception :

Uncaught ReferenceError: reCaptchaArray is not defined , we check \Views\FormBuilder\FieldTemplates\ReCaptcha.cshtml and the initialization of the array was in code check if the edit mode.

**Comment by YF82** [comment]
simple check $(document).ready(function() {
      reCaptchaArray.push(
}

fix the issue

**Comment by bill-barron** [comment]
This issue is occurring because [formsextensions.validate.js](https://github.com/bartverdonck/Sitecore-Forms-Extensions/blob/master/src/Feature/FormsExtensions/code/sitecore%20modules/Web/ExperienceForms/scripts/formsextensions.validate.js) is loading and executing after the scripts within ReCaptcha.cshtml.

The scripts within [ReCaptcha.cshtml](https://github.com/bartverdonck/Sitecore-Forms-Extensions/blob/master/src/Feature/FormsExtensions/code/Views/FormBuilder/FieldTemplates/ReCaptcha.cshtml) expect reCaptchaArray to already be defined but since [formsextensions.validate.js](https://github.com/bartverdonck/Sitecore-Forms-Extensions/blob/master/src/Feature/FormsExtensions/code/sitecore%20modules/Web/ExperienceForms/scripts/formsextensions.validate.js) has not loaded yet, the array is undefined. Even if you did define reCaptchaArray in [ReCaptcha.cshtml](https://github.com/bartverdonck/Sitecore-Forms-Extensions/blob/master/src/Feature/FormsExtensions/code/Views/FormBuilder/FieldTemplates/ReCaptcha.cshtml) it would get wiped out when [formsextensions.validate.js](https://github.com/bartverdonck/Sitecore-Forms-Extensions/blob/master/src/Feature/FormsExtensions/code/sitecore%20modules/Web/ExperienceForms/scripts/formsextensions.validate.js) executes.

To fix this, in [formsextensions.validate.js](https://github.com/bartverdonck/Sitecore-Forms-Extensions/blob/master/src/Feature/FormsExtensions/code/sitecore%20modules/Web/ExperienceForms/scripts/formsextensions.validate.js) on line 6, change this

`var reCaptchaArray = [];`

to

`var reCaptchaArray = reCaptchaArray || [];`

In [ReCaptcha.cshtml](https://github.com/bartverdonck/Sitecore-Forms-Extensions/blob/master/src/Feature/FormsExtensions/code/Views/FormBuilder/FieldTemplates/ReCaptcha.cshtml) between lines 33 and 34, add this line:

`var reCaptchaArray = reCaptchaArray || [];`

With these changes, the reCaptcha functionality will work regardless of which order the scripts are executed in.

**Comment by bartverdonck** [comment]
Fixed in 3.0

**Comment by bartverdonck** [comment]
Fixed in 2.3 as well.
