### ISSUE TITLE
Multiple files uploaded to file upload path for a multi page form

### ISSUE THREAD

**Issue by darthgushter** [bartverdonck/Sitecore-Forms-Extensions#69]
Hello,

First of all thank you for the great work you have done with the form extensions module it works like a charm but we encountered a minor "bug" in a multi page form.

On the first page we have a file upload component. This component adds a file to the server every time a user clicks next.
For example if we have 3 steps then at the end when the final submit is clicked we end up with 3 versions of the same file on the server.

I have read the issues and saw that you fixed this but it seems to happen again on the latest version. Even checked the commit and JavaScript. 

Not sure how to fix this, should I overwrite the executeSubmit? from **Feature.FormsExtensions.Pipelines.ExecuteSubmit**?

or this is the expected behavior because otherwise at the end you will not have the file because the form is AJAX?

Regards,
Vio

**Comment by bartverdonck** [comment]
Hi, 

First of all, sorry for the very delayed response. 

Since version 9.3, the file upload component is now part of the standard functionality of Sitecore forms. The component has been erased from SFE 3.0 onwards. Currently, I only support SFE3+. For older versions (like in your case), I invite you to have a look at the open source code.

Kind Regards,

Bart
