### ISSUE TITLE
RawHtml field changes '<br/>' to '<br></div>' and breaks form

### ISSUE THREAD

**Issue by cmiddletonUk** [bartverdonck/Sitecore-Forms-Extensions#77]
I have created a form using the Forms application and then dragged a RawHtml element into the form, where I then input a self-closing line break tag `<br/>` but when I click the apply button the field value is changed from `<br/>` to `<br></div>`.
This cause the form to break upon saving, deleting many elements.

I have attached a screen-recording of this occurring.
[sitecore-form-builder-rawhtml-br-issue.zip](https://github.com/bartverdonck/Sitecore-Forms-Extensions/files/4205419/sitecore-form-builder-rawhtml-br-issue.zip)

**Comment by bartverdonck** [comment]
Hi,

1) I was able to reproduce this issue.
The problem seems to be somewhere deep inside the javascript of Sitecore Forms.
The call to the server /sitecore/api/forms/client/formfield/reloadfield?sc_formmode=edit&sc_formlang=en&sc_site=shell is sending and returning the correct values.

Didn't find where it actually goes wrong in the SC Forms javascript.

I consider this a bug in Sitecore Forms rather then the extension module.

2) If the entire html is wrapped inside a div, the problem doesn't occur. (e.g. <div> test <br /></div>)
You can also bypass the issue by using <br></br>


Hopefully this can help.

Br,
